---
title: "Day 7 lecture"
output: html_document
---

# Outline
  - HW 6 review
  - Tweaking plots
  - Exercises & review

# HW 6 review

# Tweaking plots

## "convenience" and "conceptual"
## axis labels

```{r}
library(tidyr)
library(reshape2)
library(ggplot2)
library(dplyr)

myris <- iris
myris$plant <- 1:nrow(myris)
myris <- gather(myris, myvariable, cm, 1:4)
myris <- separate(myris, myvariable, c("part", "dimension"), sep = "\\.")
myris$part <- as.factor(myris$part)
myris$dimension <- as.factor(myris$dimension)

ggplot(myris, aes(cm)) + geom_histogram() + xlab("centimeters")

myris.cast <- dcast(myris, plant + Species + part ~ dimension, value.var = "cm")

ggplot(myris.cast, aes(x = Length, Width)) + geom_point() + xlab("length of the plant") + ylab("width of the plant")

```

## legend

```{r}
myris.scatter <- ggplot(myris.cast, aes(x = Length, Width)) + geom_point(aes(color = Species), size = 4)
myris.scatter
myris.scatter + theme(legend.position = "top")
myris.scatter + theme(legend.position = "none")

```

## scales

```{r}
myris.scatter + scale_x_continuous(labels = c("two", "four", "six", "eight"), breaks = c(2, 4, 6, 8))
myris.scatter + scale_x_continuous(breaks = 1:8, labels = c("two", "four", "six", "eight", "red", "green", "up", "down"))

myris.scatter + scale_x_continuous(breaks = seq(1, 8, .3))


```

## color control

```{r}
myris.scatter + scale_color_manual(values = c("red", "blue", "green"))

# RGB
umd.red <- rgb(224, 58, 62, maxColorValue = 255)
umd.gold <- rgb(255, 225, 79, maxColorValue = 255)
umd.black <- rgb(0, 0, 0, maxColorValue = 255)

myris.scatter + scale_color_manual(values = c(umd.red, umd.gold, umd.black))

myris.scatter + scale_color_brewer(palette = "Set1") + theme_minimal()

my.colors <- c("pink", "seashell", umd.gold)
ggplot(myris.cast, aes(x = Length, y = Width)) + geom_point(aes(color = Species), size = 4) + scale_color_manual(values = my.colors)

```

## themes

Check out this page for LOTS of options: http://docs.ggplot2.org/current/theme.html

```{r}
myris.scatter + scale_color_brewer(palette = "Set1") + theme_minimal()
 # put theme_minimal() (or other pre-set themes) before your other theme() calls
myris.scatter + scale_color_brewer(palette = "Set1") + theme_minimal() + theme(legend.position = "none")
myris.scatter + scale_color_brewer(palette = "Set1") + theme(legend.position = "none") + theme_minimal()


```


## "overplotting" and position control

```{r}
los.fusion <- read.csv("../scottdata/los_fusion.csv")

ggplot(los.fusion, aes(x = firstval_fusion, y = secondval_fusion)) + geom_point(position = position_jitter(height = .3, width = .3))

ggplot(los.fusion, aes(x = firstval_fusion, y = secondval_fusion)) + geom_point(alpha = .1, size = 5)

los.fusion.agg <- dcast(los.fusion, firstval_fusion + secondval_fusion ~ ., fun.aggregate = length)
colnames(los.fusion.agg)[3] <- "N"

ggplot(los.fusion.agg, aes(firstval_fusion, secondval_fusion)) + geom_point(aes(size = N))

los.fusion.agg2 <- dcast(los.fusion, firstval_fusion + secondval_fusion + firstvalue.new ~ ., fun.aggregate = length)
colnames(los.fusion.agg2)[4] <- "N"

newplot <- ggplot(los.fusion.agg2, aes(firstval_fusion, secondval_fusion)) + geom_text(aes(label = firstvalue.new, size = N), position = position_jitter(height = 0, width = .4))
newplot

ggplot(los.fusion, aes(x = firstval_fusion, y = secondval_fusion)) + geom_text(aes(label = firstvalue.new, color = firstvalue.new), position = position_jitter(width = .3, height = .3)) + scale_color_manual(values = c(umd.red, umd.gold)) + theme_minimal()

ggplot(myris, aes(cm)) + geom_density(aes(fill = Species), alpha = .4)

```

## additional layers

```{r}
newplot + geom_abline(intercept = 0, slope = 1, color = "red", linetype = 2)



```


## annotation

```{r}
newplot + theme_minimal() + annotate("rect", xmin = 5.8, xmax = 6.2, ymin = 5.8, ymax = 6.2, alpha = .4) + annotate("text", label = "check out this overplotting!", x = 2, y = 5, size = 5, color = "red") + labs(title = "This great plot") + theme(plot.title = element_text(size = 20, color = "red", face = "italic"))

```
