---
title: "Day 8 Lecture"
output: html_document
---

# Review HW 7

# Loops and control
  - if else
  - for
    - counters (sets)
    - "growing" results
    - debugging
    - break, next

## if/else

```{r}
x <- 0
if(x > 1){
  print(x)
}

x <- 3
if(x > 1) {
  print("you have enough!")
} else {
  print("you need more!")
}

x <- 2
if(x > 3) {
  print("you have too many!")
} else if(x < 3) {
  print("you need more!")
} else {
  print("just right!")
}

result <- ifelse(x > 3, "yay", "oh no!")

x <- 4
result <- ifelse(x > 3, "yay", ifelse(x < 3, "well, okay", "oh no!"))
result

```

## for loops

```{r}
mydf <- data.frame(x = rnorm(n = 1000000, mean = 2, sd = 1), group = rep(1:1000, each = 1000))

rep(1:3, 3)
rep(1:3, each = 3)
rep(1:3, each = 3, 2)

this.vector <- mydf[mydf$group == 1, "x"]
my.answer1 <- mean(this.vector)
this.vector <- mydf[mydf$group == 2, "x"]
my.answer2 <- mean(this.vector)
this.vector <- mydf[mydf$group == 3, "x"]
my.answer3 <- mean(this.vector)

# MAKE IT A LOOP

for(my.counter in 1:10) {
  print(my.counter * 2)  
}

for(i in c(9, 4, 25)) {
  print(i * 2)  
}

for(this.name in c("Ally", "Bob", "Carol")) {
  print(this.name)
}

# Won't work, because loop needs "my.answer" to exist
rm(my.answer)
for(this.group in c(1, 2, 3)) {
  this.vector <-  mydf[mydf$group == this.group, "x"]
  my.answer[this.group] <- mean(this.vector)  # subset of my.answer not available because my.answer doesn't exist
}

# Will work, but may get very sloooooow
my.answer <- 1
system.time(for(this.group in 1:1000) {
  this.vector <-  mydf[mydf$group == this.group, "x"]
  my.answer[this.group] <- mean(this.vector)
})

# BEST PRACTICE
my.answer <- rep(NA, 1000)

my.groups <- c(3, 9, 5, 2)

my.answer <- vector(length = length(my.groups))
for(this.counter in 1:length(my.groups)) {
  this.group <- my.groups[this.counter]
  this.vector <- mydf[mydf$group == this.group, "x"]
  my.answer[this.counter] <- mean(this.vector)
}

library(MASS)
mu.sigmas <- data.frame(mean1 = c(0, 0.1, -0.1, -0.3, 0.25), mean2 = c(0.2, 0.0, 0.3, -0.15, -0.1), corr = c(.2, .4, .1, .35, -0.3))

data.sets <- list()
length(data.sets) <- 5
for(i in 1:5) {
  data.sets[[i]] <- data.frame(mvrnorm(n = 1000, mu = c(mu.sigmas[i, "mean1"], mu.sigmas[i, "mean2"]), Sigma = matrix(c(1, mu.sigmas[i, "corr"], mu.sigmas[i, "corr"], 1), ncol = 2)))
  data.sets[[i]]$set <- i
  write.csv(data.sets[[i]], file = paste("sampledata", i, ".csv", sep = ""), row.names = FALSE)
}

N <- 5
mydataframes <- list()
length(mydataframes) <- N
for(set.num in 1:N) {
  mydataframes[[set.num]] <- read.csv(paste("sampledata", set.num, ".csv", sep = ""))
}

library(dplyr)
mydata <- rbind_all(mydataframes)  

my.results <- data.frame(correlation = rep(NA, 5), t = NA, df = NA, p = NA)
for(counter in c(1, 5, 3, 4, 2)) {
  my.cor.test <- cor.test(mydata$X1[mydata$set == counter], mydata$X2[mydata$set == counter])
  mycor <- my.cor.test$estimate
  myt <- my.cor.test$statistic
  mydf <- my.cor.test$parameter
  mypval <- my.cor.test$p.value
  my.results[counter, ] <- c(mycor, myt, mydf, mypval)
}

my.ttest.results <- data.frame(mean1 = rep(NA, 5), mean2 = NA, t = NA, df = NA, p = NA)
for(counter in 1:5) {
  this.ttest <- t.test(mydata$X1[mydata$set == counter], mydata$X2[mydata$set == counter])
  this.mean1 <- this.ttest$estimate[1]
  this.mean2 <- this.ttest$estimate[2]
  this.t <- this.ttest$statistic
  this.df <- this.ttest$parameter
  this.pval <- this.ttest$p.value
  my.ttest.results[counter, ] <- c(this.mean1, this.mean2, this.t, this.df, this.pval)
}

```

# simulating data

```{r}
n.sim <- 10000
sample.n <- 100
null.results <- data.frame(iteration = 1:n.sim, p = NA)
null.cortable <- matrix(c(1, 0, 0, 1), ncol = 2)
null.cortable
for(counter in 1:n.sim) {
  this.data <- data.frame(mvrnorm(sample.n, mu = c(0, 0), Sigma = null.cortable))
  this.cortest <- cor.test(this.data$X1, this.data$X2)
  null.results[counter, "p"] <- this.cortest$p.value
}
null.results$sig <- ifelse(null.results$p < .05, TRUE, FALSE)

n.sim <- 10000
sample.n <- 80
sim.results <- data.frame(iteration = 1:n.sim, p = NA, cor = NA)
sim.cortable <- matrix(c(1, .2, .2, 1), ncol = 2)
sim.cortable
for(counter in 1:n.sim) {
  this.data <- data.frame(mvrnorm(sample.n, mu = c(0, 0), Sigma = sim.cortable))
  this.cortest <- cor.test(this.data$X1, this.data$X2)
  sim.results[counter, "p"] <- this.cortest$p.value
  sim.results[counter, "corr"] <- this.cortest$estimate
}
sim.results$sig <- ifelse(sim.results$p < .05, TRUE, FALSE)
mean(sim.results$sig)
mean(sim.results$corr[sim.results$sig])


```


# Loop control

```{r}
n.sim <- 10
sample.n <- 80
sim.results <- data.frame(iteration = 1:n.sim, p = NA, cor = NA)
sim.cortable <- matrix(c(1, .2, .2, 1), ncol = 2)
sim.cortable
for(counter in 1:n.sim) {
  if(!counter %in% c(5, 8)) { next() }
  this.data <- data.frame(mvrnorm(sample.n, mu = c(0, 0), Sigma = sim.cortable))
  this.cortest <- cor.test(this.data$X1, this.data$X2)
  sim.results[counter, "p"] <- this.cortest$p.value
  sim.results[counter, "corr"] <- this.cortest$estimate
}
sim.results$sig <- ifelse(sim.results$p < .05, TRUE, FALSE)
mean(sim.results$sig)
mean(sim.results$corr[sim.results$sig])

```

